### ISSUE TITLE
compatibility with frozen fields

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-Multi-column-edit-window#1]
First of all: Thanks for keeping this add-on alive and sharing it.

I use Anki 2.1.9 (the compiled version from Ankiweb) on linux. I have only two addons: [Frozen-Fields](https://ankiweb.net/shared/info/516643804) and [Multi-column note editor debugged](https://ankiweb.net/shared/info/2064123047).

If I use these the "add" window is broken: the fields are only on the right half and if I click the left half it flickers: video: https://streamable.com/s/a6hw6/kakzgp . See also [this screenshot](https://imgur.com/a/CrGj9lA) from a bug report by another use on ankiweb from February. This user never posted on github as you suggested in your reply.

The same problem happens if I use the original version of [multi-column note editor](https://ankiweb.net/shared/info/3491767031) from 2017-10-22 in Anki 2.1

&nbsp;

Anki 2.0.52 : I tried with the latest versions of  [Frozen-Fields](https://ankiweb.net/shared/info/516643804) and [multi-column note editor](https://ankiweb.net/shared/info/3491767031) in Anki 2.0.52 without any other add-ons. I can't reproduce the problem in the "add" window. But I have a different problem in the browser: the fields are very narrow and only on the right, see this video: https://streamable.com/s/vk4nb/gnsojt

&nbsp;

I don't know if this can be fixed from your side. I posted here and not in the frozen fields repo for two reasons: frozen fields is more popular and you dealt with the add-on code last month whereas glutanimate hasn't touched frozen fields in over a year. 

Both add-ons are fairly popular so it would be great if they worked well together.

**Comment by ijgnd** [comment]
the code for the add-on on ankiweb is older than what you have in this repo. So I tried with the code from this repo (I ran `git clone`):

- If I run the code from your repo I have the same problem. If I change the source code of multiColumnEdit.py and set `ffFix = True` the problem in the "add" window is solved. So the detection of frozen fields doesn't seem work on my machine ?
- With `ffFix = True` I have a new problem: In the browser the fields are "broken". They look like in 2.0: 

one column:
![frozen_1column](https://user-images.githubusercontent.com/40218852/53736500-33624d00-3e8a-11e9-9015-ae790f505307.png)

two column:
![frozen_2columns](https://user-images.githubusercontent.com/40218852/53736510-3bba8800-3e8a-11e9-9819-b93f6c479615.png)

**Comment by Arthur-Milchior** [comment]
I'll eventually get a look at it, but not soon, soryy

**Comment by ijgnd** [comment]
A chance to get a fix in the coming months is a huge improvement. Given that you likely don't even use these two add-ons in combination your willingness to help others is really admirable. Thank you so much!

**Comment by sandersantema** [comment]
Sorry, that user which didn't report was me. Was quite busy at the time and because I can get quite distracted by github while not needing it for school I blocked it using irreversible host blocking (selfcontrol.app on macOS, which might not be irreversible but please do not tell me!). 

Thanks for writing up this bug report @ijgnd. 

And another thanks for @Arthur-Milchior, for your countless contributions to Anki. I'll be patiently waiting for the fix.

**Comment by Arthur-Milchior** [comment]
FYI, this add-on now incorporate Frozen Fields. So this should probably be closed
