### ISSUE TITLE
I can't find button to take up single filed exceptionally

### ISSUE THREAD

**Issue by havewisdom** [Arthur-Milchior/anki-Multi-column-edit-window#13]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/62235227/82566066-5889cb00-9bb6-11ea-8ac2-7c5ecdba3674.png">

anki. 2.1.26
and here is my add-ons 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/62235227/82566161-7820f380-9bb6-11ea-8e1e-3a41a826e065.png">

thank you for your great add-on"s"!

**Comment by Arthur-Milchior** [comment]
What mean "single filled"?

**Comment by ijgnd** [comment]
I think the OP is referring to the removed pushbutton "▾" in the lower right that in prior versions was used to open a menu to set fields to full width. 

It took me some time and getting to github to notice that you now set this more comfortably next to the field name by clicking the `«-»`/`»-«` buttons.

**Comment by Arthur-Milchior** [comment]
To be honest, I forgot to update the readme. I just did it, and added a title to the link to explain what it does, and added a shortcut so that user can change a size without using the mouse. And changing the screen shot and the ankiweb description.

**Comment by Arthur-Milchior** [comment]
By the way, @ijgnd , you're the first one to let me know that this new feature is more confortable.
I'm trying to move all field related button near to the field name. I see this user already uses "src". I did it with my version of frozen field, and with "clean html". I find it quick easier to use this way; but I don't know whether I'm the only one thinking i

**Comment by havewisdom** [comment]
Oh I understood. There has been a change. Thank you

**Comment by ijgnd** [comment]
@Arthur-Milchior: Once you know where to look it's obvious how to use it. But despite me knowing this positioning (e.g. from your "Show field's source (html) in editor" and your frozen fields version from last night) it took me a while to figure this out here. Maybe add a big bold red arrow on future screenshots? I can send a pull request.

**Comment by Arthur-Milchior** [comment]
I would clearly appreciate it. I have too many things right now planned to have any desire to do good screenshot
