### ISSUE TITLE
New Add-on crashs

### ISSUE THREAD

**Issue by alexk296** [Arthur-Milchior/anki-Multi-column-edit-window#14]
Hi,
I just downloaded the newest update of your (awesome) add-on. But when I open Anki this error is displayed, then Anki starts without the add-on. Guess I'm not the only one having trouble with it, as someone else posted a comment on ankiweb.net/shared that the newest update doesn't work on his Anki either.

I use:
Anki Version 2.1.22 (0ecc189a)
Windows 10

![grafik](https://user-images.githubusercontent.com/65771227/82670735-ff657a00-9c3d-11ea-94d2-c7431c150cb0.png)

**Comment by Arthur-Milchior** [comment]
Thank you, I didn't realize that the new version used features introduced so recently that even 2.1.22 didn't have it. I'll put back an outdated version for those older anki

**Comment by Arthur-Milchior** [comment]
Can you please either update anki or the add-on and let me know if it works.

**Comment by alexk296** [comment]
I updated the add-on and it works again. Great! Thank you so much!

**Comment by Arthur-Milchior** [comment]
You're welcome. Sorry for not checking with older anki. My bad
