### ISSUE TITLE
This super awesome add-on doesn't work post 2.1.49

### ISSUE THREAD

**Issue by mnhende2** [Arthur-Milchior/anki-Multi-column-edit-window#30]
@Arthur-Milchior Thanks for all the incredible work you do with Anki.  AnkiDroid and your add-ons are great!!  Much appreciated by millions.  

Unfortunately, the multi-column editor add-on hasn't doesn't work starting 2.1.50.  I've been holding off on upgrading to the latest version of Anki hoping that this add-on would get updated.  But today I did the upgrade, and am already missing this add-on.  Any chance of posting an 2.1.50+ compatible version soon?  If yes, many thanks in advance!

**Comment by hssm** [comment]
I have made [a new version](https://github.com/hssm/multi-column-note-editor2) of this add-on that works with the current version of Anki (24.11+). Thought you and @Arthur-Milchior would like to know.

**Comment by Arthur-Milchior** [comment]
thank you so much!
