### ISSUE TITLE
loading failed

### ISSUE THREAD

**Issue by cobert** [Arthur-Milchior/anki-Multi-column-edit-window#9]
![image](https://user-images.githubusercontent.com/37440266/74584684-044bd980-5010-11ea-9b03-74129759b74a.png)

I have the module in my library.
![image](https://user-images.githubusercontent.com/37440266/74584829-60fbc400-5011-11ea-8cf8-3953041f9a53.png)

**Comment by Arthur-Milchior** [comment]
Can you please let me now which version of anki you use ? I should probably state that the add-on does not work with version before .17 I think

**Comment by Arthur-Milchior** [comment]
I assume you're a python dev' since you use Anaconda.
Anki comes in with its own virtual environment. So it does not use your library, unless you start it from source code; which I assume you don't because there is no reason for anyone to do it appart from dev's

**Comment by Arthur-Milchior** [comment]
Okay, that should be corrected no

**Comment by cobert** [comment]
anki version 2.1.15

**Comment by Arthur-Milchior** [comment]
Did you update ? Is it corrected ?

**Comment by cobert** [comment]
after upgrade to version 2.1.20，it works.
thank you very much
